/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-06T10:04:32.590Z[GMT]")
@Api(value = "file", description = "the file API")
public interface FileApi {

    @ApiOperation(value = "send a Base64URL encoded executable to the server", nickname = "sendBase64URL", notes = "Whatever executable is sent to the server will be echoed back", response = byte[].class, tags = {"Test",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = byte[].class)})
    @RequestMapping(value = "/file",
            produces = {"text/plain"},
            consumes = {"text/plain"},
            method = RequestMethod.POST)
    ResponseEntity<byte[]> sendBase64URL(@ApiParam(value = "", required = true) @Valid @RequestBody byte[] body);

}
