/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-06T10:04:32.590Z[GMT]")
@Api(value = "message", description = "the message API")
public interface MessageApi {

    @ApiOperation(value = "sends a string to the server", nickname = "sendMessage", notes = "Whatever string is sent to the server will be echoed back", response = String.class, tags = {"Test",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Echo of the message sent", response = String.class)})
    @RequestMapping(value = "/message",
            produces = {"text/plain"},
            consumes = {"text/plain"},
            method = RequestMethod.POST)
    ResponseEntity<String> sendMessage(@ApiParam(value = "", required = true) @Valid @RequestBody String body);

}
